language: node_js

node_js: 10

services:
  - docker

script:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD" quay.io
  - ./build.sh
  - sudo ./test.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
